---
- name: Install Ansible Product Demos
  hosts: localhost

  vars:
    aap_postinstall_repo_url: https://github.com/ansible/product-demos-postinstall.git
    aap_postinstall_repo_ref: main
    aap_postinstall_dir: '{{ playbook_dir }}/product-demos-postinstall'
    aap_postinstall_ignore_files: []

  tasks:
    - name: Check out product-demos-postinstall repo
      ansible.builtin.git:
        repo: '{{ aap_postinstall_repo_url }}'
        dest: '{{ aap_postinstall_dir }}'
        version: '{{ aap_postinstall_repo_ref }}'
        force: true

    - name: Include product-demos-postinstall variables
      ansible.builtin.include_vars:
        dir: '{{ aap_postinstall_dir }}'
        extensions:
          - yml
          - yaml
        ignore_files: '{{ aap_postinstall_ignore_files }}'
        ignore_unknown_extensions: true

    - name: Execute automation controller resource configuration
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch

    - name: Print user message
      ansible.builtin.debug:
        msg: "{{ user_message }}"
      when: user_message is defined

...
